#
# Run OVMS server
# set the configuration in ./conf/
#
# The container will initialize the DB (DEMO car and user Joe-the-Owner)
#
FROM alpine:latest
RUN apk update
RUN apk add git sed bash perl netcat-openbsd mysql-client make tzdata
# needed for PW hashing
RUN apk add apache2-utils
# Required perl modules
# perl-anyevent-http not available in Alpine, install via cpanm below
RUN apk add perl-dbi perl-dbd-mysql perl-digest-hmac perl-config-inifiles perl-uri perl-json-xs
# perl-ev and perl-object-event not available in Alpine, install via cpanm below
RUN apk add perl-crypt-rc4 perl-data-uuid perl-protocol-websocket perl-anyevent perl-app-cpanminus
# needed for Net::APNS::Simple
RUN apk add perl-cryptx perl-protocol-http2 perl-crypt-jwt perl-io-socket-ssl perl-role-tiny perl-module-build-tiny
RUN apk add perl-extutils-helpers perl-extutils-config perl-moo perl-sub-quote
# needed for compiling C-based Perl modules (EV, etc.)
RUN apk add perl-dev linux-headers gcc make musl-dev

RUN cpanm EV
RUN cpanm Object::Event
RUN cpanm AnyEvent::HTTP
RUN cpanm AnyEvent::HTTPD
RUN cpanm Net::APNS::Simple

RUN mkdir -p /usr/src/app

# Pin the upstream OVMS server source for reproducible builds.
# You can override this at build time with:
#   docker compose build --build-arg OVMS_REF=<sha>
ARG OVMS_REF=4471da2cd71e15e824ffdfcef12e92e281e6ec07

# Do a shallow fetch of the exact ref (fast + reproducible).
RUN mkdir -p /usr/src/app/ovms \
  && git -C /usr/src/app/ovms init \
  && git -C /usr/src/app/ovms remote add origin https://github.com/openvehicles/Open-Vehicle-Server.git \
  && git -C /usr/src/app/ovms fetch --depth 1 origin ${OVMS_REF} \
  && git -C /usr/src/app/ovms checkout FETCH_HEAD

RUN cp -r /usr/src/app/ovms/v3/server  /usr/src/app/server
RUN rm -rf /usr/src/app/ovms

# CRYPT::RC4::XS not available and cpanm fails -> utilize Crypt::RC4 instead
RUN find /usr/src/app -regex '.*\.\(pl\|pm\)' -exec sed -i -e 's/RC4::XS/RC4/g' {} \;

# Apply local patches (fails the build if upstream changed and patch doesn't apply cleanly)
COPY ./patches /usr/src/app/patches
RUN cd /usr/src/app/server \
  && find . -name ApiHttpCore.pm && git apply -p3 --verbose ../patches/0001-apihttpcore-basic-auth.patch

COPY ./scripts/manage-db.sh  /usr/src/app
RUN chmod +x /usr/src/app/manage-db.sh
COPY ./scripts/check-and-run.sh  /usr/src/app
RUN chmod +x /usr/src/app/check-and-run.sh
WORKDIR /usr/src/app
ENTRYPOINT [ "/usr/src/app/check-and-run.sh" ]


